name: Java Maven Build

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted  # Specify that this job runs on a self-hosted runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Build with Maven
    - name: Build with Maven
      run: cd C:

    # # Display Java version
    # - name: Display Java version
    #   run: java -version

    # # Display Maven version
    # - name: Display Maven version
    #   # run: mvn -version
