name: Backup Folder to Remote Server

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  backup:
    runs-on: self-hosted  # Specify the runner where the folder to be copied exists

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        $key = "${{ secrets.SSH_PRIVATE_KEY }}"
        $keyPath = "$env:USERPROFILE\.ssh\id_rsa"
        if (-not (Test-Path "$env:USERPROFILE\.ssh")) {
          New-Item -ItemType Directory -Path "$env:USERPROFILE\.ssh"
        }
        $key | Out-File -FilePath $keyPath -Encoding ascii
        icacls $keyPath /inheritance:r /grant:r $env:USERNAME:F
        Start-Process "ssh-add" $keyPath -NoNewWindow -Wait

    - name: Copy Folder to Remote Server
      shell: pwsh
      run: |
        $sourcePath = "C:\Windows\system32\actions-runner"
        $destinationPath = "C:\Windows\"
        $serverName = "13.235.245.155"
        $username = "Administrator"
        $sshKeyPath = "${{ secrets.SSH_KEY_PATH }}"
        scp -i $env:USERPROFILE\.ssh\id_rsa -r $sourcePath $username@$serverName:$destinationPath
